apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kzex0kvkd-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:f8d8fd2bc1b97e7efe0289a1cb138ea53b6e57da@sha256:21d45cd0bb922871fc74eecc519fd368e77a786234b322e89bf1699cf3a4758e
          name: container-image
